### ISSUE TITLE
"Junior to regular developer" naming

### ISSUE THREAD

**Issue by resulselmani16** [kealanparr/Every-link-I-wish-I-had-as-a-beginner#5]
There is something about this naming that can be misinterpreted or misunderstood. I don't think that this naming is maybe "correct" as the term "regular" can be different for each person. I suggest to maybe use something like "mid-level" or something like that in order to be understood better and clearer.

**Comment by kealanparr** [comment]
@resulselmani16 

This sounds like a good idea :)

Would you like to fix it? Are you familiar with Git and GitHub? 

If not, I can fix it very quickly. I just don't want to steal your thunder 😉

**Comment by resulselmani16** [comment]
@kealanparr Yes. I will fix it real quick. Don't get me wrong, though. All love and respect for this whole thing you did 😊

**Comment by kealanparr** [comment]
@resulselmani16

People like you push the whole open source community forwards.

Raising issues and helping clarifying things, I appreciate you taking the time to raise the issue - thank you!

**Comment by resulselmani16** [comment]
@kealanparr 

Thank you for this whole article man.

But in the meantime, I can't push the changes as it's giving me this error:

` Permission to kealanparr/Every-link-I-wish-I-had-as-a-beginner.git denied to resulselmani16.`

**Comment by kealanparr** [comment]
@resulselmani16

I think the problem is that 

1. you need to fork the codebase
2. push your changes to your version of `master`
3. create a pull request to merge your fork with mine

:)

**Comment by resulselmani16** [comment]
@kealanparr got it.

Done it and now it works perfectly. The PR is open now! :)

**Comment by kealanparr** [comment]
@resulselmani16
Let's move our convo the pull request then! :)
